fish_vi_key_bindings

# Git
alias g="git"
alias gs="git status"
alias gcm="git commit -a -m"
alias glo="git log --oneline --all --graph"

# DotNet
# alias dnt="dotnet test"
# alias dnrb="dotnet build --no-incremental"
# set PATH "$HOME/.dotnet/tools:$PATH"

# Vim
alias vio="vi --cmd 'let g:enableOmniSharp=1'"
set --export EDITOR "vi"

# Grep
alias greppt="grep --color -r --include='*.cs' --exclude-dir='AutoGenerated' $argv"
alias grepcs="grep --color -r --include='*.cs' $argv"

# ls
alias ll="ls -l -h -A --color=auto $argv"
alias ls="ls -A --color=auto"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# eval ~/miniconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<

