fish_vi_key_bindings

# Git
alias g="git"
alias gs="git status"
alias gcm="git commit -a -m"
alias glo="git log --oneline --all --graph"

# DotNet
alias dnt="dotnet test"
alias dnrb="dotnet build --no-incremental"

# Vim
alias vi="nvim"

# Grep
alias greppt="grep --color -r --include='*.cs' --exclude-dir='AutoGenerated' $argv"
alias grepcs="grep --color -r --include='*.cs' $argv"

# ls
alias ll="ls -l -h $argv"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /home/patra/miniconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<
